accounts:
  - name: alice
    coins: ["2000000000TFT"]
  - name: bob
    coins: ["1000000000TFT"]
validator:
  name: alice
  staked: "1000000000TFT"
client:
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["100000TFT"]
